// <auto-generated />
using System;
using Katiba55.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Katiba55.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250812150538_RemoveBoqNumberUniqueness")]
    partial class RemoveBoqNumberUniqueness
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("Katiba55.API.Entities.Advance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContractId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Percent")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.ToTable("Advances");
                });

            modelBuilder.Entity("Katiba55.API.Entities.BOQ", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Value")
                        .HasColumnType("TEXT");

                    b.Property<int?>("WorkId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("WorkId");

                    b.ToTable("BOQs");
                });

            modelBuilder.Entity("Katiba55.API.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApprovalImagePath")
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("RepresentativeName")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Katiba55.API.Entities.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BOQId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Number")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("BOQId")
                        .IsUnique();

                    b.HasIndex("Number");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("Katiba55.API.Entities.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContractId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("Katiba55.API.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ActualEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ActualStartDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EstimatedEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EstimatedStartDate")
                        .HasColumnType("TEXT");

                    b.Property<double?>("ExecutedValue")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("ExecutionDate")
                        .HasColumnType("TEXT");

                    b.Property<double?>("ExecutionPercent")
                        .HasColumnType("REAL");

                    b.Property<int>("ExecutionStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("RelativeWeightPercent")
                        .HasColumnType("REAL");

                    b.Property<double?>("RemainingValue")
                        .HasColumnType("REAL");

                    b.Property<double?>("TotalValue")
                        .HasColumnType("REAL");

                    b.Property<int>("WorkId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("WorkId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Katiba55.API.Entities.Media", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReferenceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReferenceType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowInExecutionStatusPage")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Size")
                        .HasColumnType("REAL");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Medias");
                });

            modelBuilder.Entity("Katiba55.API.Entities.Officer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("JoinDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LeaveDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Officers");
                });

            modelBuilder.Entity("Katiba55.API.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ActualEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ActualStartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("BenefitingSide")
                        .HasColumnType("TEXT");

                    b.Property<double?>("EstimatedCost")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("EstimatedEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EstimatedStartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutingSide")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExecutionDate")
                        .HasColumnType("TEXT");

                    b.Property<double?>("ExecutionPercent")
                        .HasColumnType("REAL");

                    b.Property<int>("ExecutionStatus")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("FinancialAllocation")
                        .HasColumnType("REAL");

                    b.Property<double?>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("SupervisorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("SupervisorId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Katiba55.API.Entities.ProjectExecutionHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<double>("Percentage")
                        .HasColumnType("REAL");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectExecutionHistories");
                });

            modelBuilder.Entity("Katiba55.API.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastLoginDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Katiba55.API.Entities.Work", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ActualEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ActualStartDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EstimatedEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EstimatedStartDate")
                        .HasColumnType("TEXT");

                    b.Property<double?>("ExecutedValue")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("ExecutionDate")
                        .HasColumnType("TEXT");

                    b.Property<double?>("ExecutionPercent")
                        .HasColumnType("REAL");

                    b.Property<int>("ExecutionStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("RelativeWeightPercent")
                        .HasColumnType("REAL");

                    b.Property<double?>("RemainingValue")
                        .HasColumnType("REAL");

                    b.Property<double?>("TotalValue")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Works");
                });

            modelBuilder.Entity("Katiba55.API.Entities.WorkCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("WorkId");

                    b.ToTable("WorkCompanies");
                });

            modelBuilder.Entity("Katiba55.API.Entities.WorkExecutionHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<double>("Percentage")
                        .HasColumnType("REAL");

                    b.Property<int>("WorkId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WorkId");

                    b.ToTable("WorkExecutionHistories");
                });

            modelBuilder.Entity("Katiba55.API.Entities.Advance", b =>
                {
                    b.HasOne("Katiba55.API.Entities.Contract", "Contract")
                        .WithMany("Advances")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("Katiba55.API.Entities.BOQ", b =>
                {
                    b.HasOne("Katiba55.API.Entities.Company", "Company")
                        .WithMany("BOQs")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Katiba55.API.Entities.Project", "Project")
                        .WithMany("BOQs")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Katiba55.API.Entities.Work", "Work")
                        .WithMany("BOQs")
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Company");

                    b.Navigation("Project");

                    b.Navigation("Work");
                });

            modelBuilder.Entity("Katiba55.API.Entities.Contract", b =>
                {
                    b.HasOne("Katiba55.API.Entities.BOQ", "BOQ")
                        .WithOne("Contract")
                        .HasForeignKey("Katiba55.API.Entities.Contract", "BOQId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BOQ");
                });

            modelBuilder.Entity("Katiba55.API.Entities.Invoice", b =>
                {
                    b.HasOne("Katiba55.API.Entities.Contract", "Contract")
                        .WithMany("Invoices")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("Katiba55.API.Entities.Item", b =>
                {
                    b.HasOne("Katiba55.API.Entities.Project", null)
                        .WithMany("Items")
                        .HasForeignKey("ProjectId");

                    b.HasOne("Katiba55.API.Entities.Work", "Work")
                        .WithMany("Items")
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Work");
                });

            modelBuilder.Entity("Katiba55.API.Entities.Media", b =>
                {
                    b.HasOne("Katiba55.API.Entities.Project", null)
                        .WithMany("Medias")
                        .HasForeignKey("ProjectId");
                });

            modelBuilder.Entity("Katiba55.API.Entities.Project", b =>
                {
                    b.HasOne("Katiba55.API.Entities.Officer", "Supervisor")
                        .WithMany("Projects")
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("Katiba55.API.Entities.ProjectExecutionHistory", b =>
                {
                    b.HasOne("Katiba55.API.Entities.Project", "Project")
                        .WithMany("ExecutionHistories")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Katiba55.API.Entities.Work", b =>
                {
                    b.HasOne("Katiba55.API.Entities.Project", "Project")
                        .WithMany("Works")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Katiba55.API.Entities.WorkCompany", b =>
                {
                    b.HasOne("Katiba55.API.Entities.Company", "Company")
                        .WithMany("WorkCompanies")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Katiba55.API.Entities.Work", "Work")
                        .WithMany("WorkCompanies")
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Work");
                });

            modelBuilder.Entity("Katiba55.API.Entities.WorkExecutionHistory", b =>
                {
                    b.HasOne("Katiba55.API.Entities.Work", "Work")
                        .WithMany("ExecutionHistories")
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Work");
                });

            modelBuilder.Entity("Katiba55.API.Entities.BOQ", b =>
                {
                    b.Navigation("Contract")
                        .IsRequired();
                });

            modelBuilder.Entity("Katiba55.API.Entities.Company", b =>
                {
                    b.Navigation("BOQs");

                    b.Navigation("WorkCompanies");
                });

            modelBuilder.Entity("Katiba55.API.Entities.Contract", b =>
                {
                    b.Navigation("Advances");

                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("Katiba55.API.Entities.Officer", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("Katiba55.API.Entities.Project", b =>
                {
                    b.Navigation("BOQs");

                    b.Navigation("ExecutionHistories");

                    b.Navigation("Items");

                    b.Navigation("Medias");

                    b.Navigation("Works");
                });

            modelBuilder.Entity("Katiba55.API.Entities.Work", b =>
                {
                    b.Navigation("BOQs");

                    b.Navigation("ExecutionHistories");

                    b.Navigation("Items");

                    b.Navigation("WorkCompanies");
                });
#pragma warning restore 612, 618
        }
    }
}
